# Site settings
title: Flow Paragliding
email: flowparagliding@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Flow Paragliding school. edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://locahost:4000" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
